
import React from 'react';
import { ChatMessage as ChatMessageType } from '../types';
import StatuteCard from './StatuteCard';

interface Props {
  message: ChatMessageType;
}

const ChatMessage: React.FC<Props> = ({ message }) => {
  const isUser = message.role === 'user';

  const generateMemo = () => {
    const memoContent = `
LEGAL LENSE: STATUTORY ANALYSIS MEMO
Date: ${new Date(message.timestamp).toLocaleString()}
Counsel Reference: ${message.id}

ANALYSIS:
${message.content}

RELEVANT STATUTES:
${message.data?.relevantStatutes.map(s => `• ${s.actName} - ${s.section}: ${s.title}\n  ${s.description}`).join('\n\n')}

SOURCES:
${message.data?.sources.map(s => `• ${s.title} (${s.uri})`).join('\n')}

This analysis is generated by Legal Lense Jurisprudence Engine.
    `.trim();

    const blob = new Blob([memoContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Legal_Memo_${message.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={`flex w-full mb-12 ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`flex gap-6 max-w-[92%] sm:max-w-[85%] ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
        <div className={`w-14 h-14 rounded-2xl flex-shrink-0 flex items-center justify-center text-sm shadow-lg border ${
          isUser ? 'bg-[#1A2B4B] text-white border-slate-800' : 'bg-white text-[#1A2B4B] border-slate-100'
        }`}>
          {isUser ? <i className="fas fa-user-graduate"></i> : <i className="fas fa-building-columns"></i>}
        </div>
        
        <div className="space-y-4 flex-1">
          <div className={`p-10 rounded-[2.5rem] border relative overflow-hidden ${
            isUser 
              ? 'bg-[#1A2B4B] text-white border-slate-800 rounded-tr-none shadow-2xl shadow-blue-900/10' 
              : 'bg-white text-slate-700 border-slate-100 rounded-tl-none shadow-xl shadow-slate-200/50'
          }`}>
            <div className={`whitespace-pre-wrap text-[16px] leading-relaxed font-medium tracking-normal ${isUser ? 'font-semibold' : 'font-medium text-[#1e293b]'}`}>
              {message.content}
            </div>
            
            {message.data && message.data.relevantStatutes.length > 0 && (
              <div className="mt-12 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
                <div className="flex items-center gap-5 mb-8">
                  <span className="text-[10px] font-black uppercase tracking-[0.4em] text-amber-600 px-4 py-1.5 bg-amber-50 rounded-full border border-amber-100">
                    Statutory Citations
                  </span>
                  <div className="h-[1px] flex-1 bg-gradient-to-r from-slate-200 to-transparent"></div>
                </div>
                <div className="grid gap-6">
                  {message.data.relevantStatutes.map((s) => (
                    <StatuteCard key={s.id} statute={s} />
                  ))}
                </div>
              </div>
            )}

            {!isUser && (
              <div className="mt-10 pt-8 border-t border-slate-50 flex justify-end">
                <button 
                  onClick={generateMemo}
                  className="flex items-center gap-2 px-5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-[11px] font-black uppercase tracking-widest text-slate-500 hover:bg-[#1A2B4B] hover:text-white hover:border-[#1A2B4B] transition-all group"
                >
                  <i className="fas fa-file-pdf group-hover:scale-110 transition-transform"></i>
                  Generate Formal Memo
                </button>
              </div>
            )}

            {message.data && message.data.sources && message.data.sources.length > 0 && (
              <div className="mt-10 pt-10 border-t border-slate-50">
                <h5 className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-300 mb-6 flex items-center gap-3">
                  <span className="w-2 h-2 bg-[#1A2B4B]/10 rounded-full"></span>
                  Verification Logs
                </h5>
                <div className="flex flex-wrap gap-4">
                  {message.data.sources.map((source, idx) => (
                    <a 
                      key={idx} 
                      href={source.uri} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="group flex items-center gap-3 px-5 py-2.5 bg-slate-50 border border-slate-200 rounded-2xl text-[12px] font-bold text-slate-500 hover:bg-white hover:border-[#1A2B4B]/30 hover:text-[#1A2B4B] transition-all"
                    >
                      <i className="fas fa-up-right-from-square text-[10px] text-slate-300 group-hover:text-[#1A2B4B]"></i>
                      {source.title.length > 40 ? source.title.substring(0, 40) + '...' : source.title}
                    </a>
                  ))}
                </div>
              </div>
            )}
          </div>
          <div className={`px-6 text-[10px] text-slate-300 font-black uppercase tracking-widest ${isUser ? 'text-right' : 'text-left'}`}>
            System Memo • {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ChatMessage;
